### ISSUE TITLE
Doc: Generate all man pages for nanol CLI

### ISSUE THREAD

**Issue by leon3s** [next-hat/nanocl#11]
We should build all man page and have automatic update into the documentation.

**Comment by 0xle0ne** [comment]
You can see example of building man page in our `./bin/nanocl/src/build.rs`

**Comment by hnidoaht-101** [comment]
> We should build all man page and have automatic update into the documentation.

Just clarify. So do you mean we want to build all the man page for all crates under `./bin` and `.crates` (`nanocli_stubs` and `nanocld_client`, am I right?

**Comment by 0xle0ne** [comment]
Man pages are only related to binaries. The `bin` folder
For `nanocld` it's already done.
For `nanocl` we are missing some
